// TEMPLATE — edit this file to update the scaffold for all future projects.
// Analyst Agent — Enriched failure reporter.
// Combines heal events, root-cause diagnosis, and flaky detection into
// a single structured report written to CI artifacts and stdout.
// In Phase 3, this report is also posted to the Work Management Connector.

import fs from 'fs';
import path from 'path';
import { buildDiagnosis, appendDiagnosis } from './root-cause.js';
import { detectFlaky, isQuarantined } from './flaky-detector.js';
import { escalationCandidates } from '../pages/heal-audit-log.js';

const REPORT_PATH = process.env.ANALYST_REPORT_PATH ?? 'analyst-report.json';

/**
 * Generates the full analyst report for a CI run.
 * Call this in a Playwright global teardown or a post-test script.
 *
 * @param {object[]} failures - array of { testTitle, error, traceFile, screenshotFile }
 * @param {number} totalTests - total test count (for quarantine budget context)
 * @returns {object} report
 */
export function generateReport(failures, totalTests) {
  const diagnoses = failures.map(f => {
    const diagnosis = buildDiagnosis(f);
    appendDiagnosis(diagnosis);
    return diagnosis;
  });

  const flakyTests = detectFlaky();
  const escalations = escalationCandidates(3);
  const quarantined = failures.filter(f => isQuarantined(f.testTitle));

  const report = {
    runId: process.env.GITHUB_RUN_ID ?? 'local',
    timestamp: new Date().toISOString(),
    summary: {
      totalTests,
      failures: failures.length,
      quarantinedFailures: quarantined.length,
      blockingFailures: failures.length - quarantined.length,
      flakyDetected: flakyTests.length,
      escalations: escalations.length,
    },
    diagnoses,
    flakyTests,
    escalations,
    // Phase 3: this section will be posted to Work Management Connector
    ticketUpdates: diagnoses
      .filter(d => d.severity === 'high')
      .map(d => ({
        testTitle: d.testTitle,
        action: 'comment',
        body: formatTicketComment(d),
      })),
  };

  fs.writeFileSync(
    path.resolve(REPORT_PATH),
    JSON.stringify(report, null, 2),
    'utf8'
  );

  printSummary(report);
  return report;
}

/**
 * Reads the last generated report.
 */
export function readReport() {
  const resolved = path.resolve(REPORT_PATH);
  if (!fs.existsSync(resolved)) return null;
  return JSON.parse(fs.readFileSync(resolved, 'utf8'));
}

// ── PRIVATE ─────────────────────────────────────────────────────────────

function formatTicketComment(diagnosis) {
  return [
    `## Automated QA Report — ${diagnosis.testTitle}`,
    `**Category:** ${diagnosis.category}`,
    `**Severity:** ${diagnosis.severity}`,
    `**Summary:** ${diagnosis.summary}`,
    ``,
    `**Suggested action:** ${diagnosis.suggestedAction}`,
    ``,
    `**Repro steps:**`,
    ...diagnosis.reproSteps.map(s => `- ${s}`),
    ``,
    `*Generated by Analyst Agent — run ${diagnosis.runId}*`,
  ].join('\n');
}

function printSummary(report) {
  const { summary } = report;
  console.log('\n── Analyst Report ──────────────────────────────');
  console.log(`Run:              ${report.runId}`);
  console.log(`Total tests:      ${summary.totalTests}`);
  console.log(`Failures:         ${summary.failures}`);
  console.log(`  Blocking:       ${summary.blockingFailures}`);
  console.log(`  Quarantined:    ${summary.quarantinedFailures}`);
  console.log(`Flaky detected:   ${summary.flakyDetected}`);
  console.log(`Escalations:      ${summary.escalations}`);
  if (report.escalations.length > 0) {
    console.log('\nEscalation candidates (heal 3+ times without PR merge):');
    report.escalations.forEach(e =>
      console.log(`  - ${e.locator} (${e.count}x)`)
    );
  }
  console.log('────────────────────────────────────────────────\n');
}
